brokerConfig: |
  bootstrap.servers=localhost:9092
messageSize: 1024
name: A0_B16384
producerConfig: |
  acks=0
  linger.ms=100000
  batch.size=16384
replicationFactor: 1
topicConfig: |
  min.insync.replicas=1
