name: 1 producer,1 consumer,1 partition
numberOfTopics: 4
partitionsPerTopic: 1
messageSize: 1024
consumersPerTopic: 1
consumerBacklog: 0
producersPerTopic: 1
producerRatePerSec: 1000
benchmarkDurationMinutes: 1